
project_id = "cwjxbwqdfejhmiixoiym"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["extensions"]
# Maximum rows to return per response
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio
port = 54323
# External URL of the API server that Studio should connect to
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually delivered, rather they
# are monitored, and you can view the emails that would have been delivered from the web interface.
[inbucket]
# Port to use for the email testing server web interface
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000", "https://lovable.dev"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
# Optionally override the callback URL for this provider. Defaults to the API URL of your Supabase
# project with the path /auth/v1/callback.
# redirect_uri = ""
# Optionally provide a custom authorization endpoint, e.g., for self-hosted services.
# authorizationEndpoint = ""
# Optionally provide a custom token endpoint URL, e.g., for self-hosted services.
# tokenEndpoint = ""
# Optionally provide a custom user info endpoint URL, e.g., for self-hosted services.
# userInfoEndpoint = ""

[functions]
# Port to use for Functions API URL
port = 54326

# Define the reCAPTCHA verification function settings
[functions.verify-recaptcha]
verify_jwt = false
