
project_id = "cwjxbwqdfejhmiixoiym"

[functions.convert-to-3d]
verify_jwt = false

[functions.check-3d-status]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-web-icon]
verify_jwt = false

[functions.increment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.webhook-stripe]
verify_jwt = false

[functions.text-to-3d]
verify_jwt = true

[functions.check-text-to-3d-status]
verify_jwt = true
