
# This file controls the behavior of Supabase Edge Functions.
project_id = "cwjxbwqdfejhmiixoiym"

[functions.convert-to-3d]
verify_jwt = false

[functions.check-3d-status]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.increment]
verify_jwt = false
